name: Release

on:
  push:
    # run only against tags
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: nix build .
      - name: Zip
        run: (cd ./result && zip -r - .) > "pocketvector_$(echo $GITHUB_REF_NAME | sed 's/v//g')_linux_amd64.zip" 
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE
            ./*.zip
